Merge dev branch to main
BreakTools/LightGroupMixer pull request #1
Opened 2023-12-07 10:03 UTC by mervinvb

2023-12-14 11:44 UTC, gillesvink requested changes
Really nice! I can really notice how code quality improved for you, well done :)

I wrote a few comments that can help improve it a little bit

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/LightGroupGrade.gizmo
> +version 13.2 v3
For gizmo's its best to remove those two lines, only add these if you really use nodes that would break compatibility. Else if you use this script in for example 13.1, it will show a warning (which would not be necessary).

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/LightGroupGrade.gizmo
> +Gizmo {
Does it need to be a gizmo or could it be a group (Group has a big advantage as it could be send to anyone who does not have this toolset installed)

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/LightGroupGrade.gizmo
> + addUserKnob {20 User}
Its nice to always name the user tab to something else. User is default, I tend to name the knob MyNodeControlsTab and then the label MyNode

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/init.py
> +import light_group_mixer
Rename this file to menu.py to prevent loading in non-gui environments

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    if channels is None:
Could also be:

```python
if not channels:
```

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +def _get_lightgroups(lightgroup_mixer_node: nuke.Node, channels) -> tuple:
If you return a tuple, it can be specified what kind of data the tuple contains:
For example:
```python
tuple[str, int]
```

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    """This function returns all the lightgroups and the lightgroups we still need to build."""
I would specify the args here as well and what is returned

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +        if not channel.endswith("blue"):
Might be better to check for layer in nuke.layers() instead, and then check how many subchannels it contains (at least 3).

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +        if not channel.startswith("LG_"):
Things like quite important constants could be defined in a constants file or at top level of this script.

```python
LIGHTGROUP_PREFIX = "LG_"

if not channel.startswith(LIGHTGROUP_PREFIX)
```

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +        all_lightgroups.append(channel.split(".")[0])
With nuke.layers() this would not be necessary

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +        if f"{channel.split('.')[0]}_tab_begin" in all_knobs:
If the all_knobs would be a dataclass, a method could be introduced to check if the layer is already in the knobs

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    all_lightgroups = []
I think it could be improved structure wise if we introduce dataclasses for the data thats contained here. Also makes it easier for returning (instead of a tuple)

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +def _get_node_to_connect_to() -> nuke.Node:
Is this function called within the gizmo/group (if its within a gizmo, definitely change it to a group as gizmo's cant store what's changed inside)

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    """This function creates grader nodes and adds the proper menu items."""
Would be good to write args here

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    lightgroups_to_build, to_connect_to, lightgroup_mixer_node: nuke.Node
Would be good to rename the arguments. For example to_connect_to doesn't really describe what it is. Probably node_to_connect_to describes it better.

Also add some typehints to the arguments

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +    light_group_name = f"{lightgroup.split('LG_')[1].split('.')[0]}"
If we use a constant this can be referenced directly

2023-12-14 11:44 UTC, gillesvink commented on light_group_mixer/light_group_mixer.py
> +        if node.Class() == "LightGroupGrade":
Try to invert this statement so we prevent a lot of indents.

```python
for node in lightgroup_mixer_node.nodes():
    if node.Class() != LIGHTGROUP_GRADE_NAME:
         continue
     if node.name() not in lightgroups_to_remove:
         continue
     nuke.delete(node)

2023-12-14 15:24 UTC, mervinvb commented on light_group_mixer/light_group_mixer.py
> +def _get_lightgroups(lightgroup_mixer_node: nuke.Node, channels) -> tuple:
Unfortunately this was introduced in Python 3.9, Nuke 13 is still on 3.7. Will keep it in mind for other future projects!

2023-12-14 18:55 UTC, gillesvink commented
Yes, however, you can use from __future__ import annotations

This will make it possible to use this format

On Thu, Dec 14, 2023 at 16:24, Mervin ***@***.***(mailto:On Thu, Dec 14, 2023 at 16:24, Mervin <<a href=)> wrote:

> @mervinvb commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [light_group_mixer/light_group_mixer.py](https://github.com/BreakTools/LightGroupMixer/pull/1#discussion_r1426871471):
>
>> +
> +def _get_node_to_connect_to() -> nuke.Node:
> +    """This functions returns the node our next node should connect to."""
> +    try:
> +        if nuke.toNode("Output1").input(0).Class() == "LightGroupGrade":
> +            to_connect_to = nuke.toNode("Output1").input(0)
> +        else:
> +            to_connect_to = nuke.toNode("Input1")
> +
> +    except AttributeError:
> +        to_connect_to = nuke.toNode("Input1")
> +
> +    return to_connect_to
> +
> +
> +def _get_lightgroups(lightgroup_mixer_node: nuke.Node, channels) -> tuple:
>
> Unfortunately this was introduced in Python 3.9, Nuke 13 is still on 3.7. Will keep it in mind for other future projects!
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/BreakTools/LightGroupMixer/pull/1#discussion_r1426871471), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AFJSKU5KKRVN4CMMTPAVN3DYJMK3JAVCNFSM6AAAAABAKY5QPOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBSGA3DSMBQGA).
> You are receiving this because your review was requested.Message ID: ***@***.***>

2023-12-15 08:44 UTC, mervinvb commented on light_group_mixer/light_group_mixer.py
> +        all_lightgroups.append(channel.split(".")[0])
nuke.layers() was giving me a list with empty strings, both with a node specified and without. Would you happen to know why? Using this code snippets from the nuke python docs now instead;

```python
channels = node.channels()
layers = list( set([c.split('.')[0] for c in channels]) )
```

2024-01-08 13:58 UTC, merged